apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}"
spec:
  replicas: 1
  selector:
    app: "{{ .Values.name }}"
    deploymentconfig: "{{ .Values.name }}"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
        deploymentconfig: "{{ .Values.name }}"
    spec:
      containers:
        - image: matomo
          imagePullPolicy: Always
          name: matomo
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: /var/www/html
              name: "{{ .Values.name }}-data"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: "{{ .Values.name }}-data"
          persistentVolumeClaim:
            claimName: "{{ .Values.name }}"
