apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}"
spec:
  replicas: 1
  selector:
    app: "{{ .Values.name }}"
    deploymentconfig: "{{ .Values.name }}"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
        deploymentconfig: "{{ .Values.name }}"
    spec:
      containers:
        - image: matomo
          env:
            - name: MATOMO_DATABASE_HOST
              value: "{{ .Values.name }}-mysql"
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: "{{ .Values.name }}-configuration"
            - name: MATOMO_DATABASE_DBNAME
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: "{{ .Values.name }}-configuration"
            - name: MATOMO_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: "{{ .Values.name }}-configuration"
            - name: MATOMO_DATABASE_TABLES_PREFIX
              value: matomo_
          imagePullPolicy: Always
          name: matomo
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
          securityContext: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: "{{ .Values.name }}-data"
      serviceAccount: matomo-runner
      serviceAccountName: matomo-runner
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: "{{ .Values.name }}-data"
          persistentVolumeClaim:
            claimName: "{{ .Values.name }}"
