apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}-matomo"
spec:
  ports:
    - name: matomo
      nodePort: 0
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: "{{ .Values.name }}-matomo"
    deploymentconfig: "{{ .Values.name }}-matomo"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
