apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}-mysql"
spec:
  ports:
    - name: mysql
      nodePort: 0
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: "{{ .Values.name }}-mysql"
    deploymentconfig: "{{ .Values.name }}-mysql"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
