{{- if .Values.development }}
apiVersion: v1
kind: Secret
metadata:
  name: lodestar-backend-configuration
type: Opaque
stringData:
  MYSQL_DATABASE: "{{ .Values.mysqlDatabase }}"
  MYSQL_ROOT_PASSWORD: "{{ .Values.mysqlRootPassword }}"
  MYSQL_USER: "{{ .Values.mysqlUser }}"
  MYSQL_PASSWORD: "{{ .Values.mysqlPassword }}"
{{- end }}
